import { decide, type Decision } from "../decision";

// Validation regex per docs/design/03-workflow.md:462, adopted over the
// owner/repo-prefixed variant at CONTRIBUTING.md:206 per this story's ISA
// Decisions section (that reconciliation is #14's job under CLAIM-9.6).
//
// Exemptions, per the table at docs/design/03-workflow.md:465-470:
//   - `Merge …`    generated by git; no issue context is available
//   - `fixup! …`   autosquash marker; inherits its target's prefix on rebase
//   - `squash! …`  same
//   - `Revert "…"` generated by `git revert`; carries the original subject
export const COMMIT_PREFIX_RE = /^(#[0-9]+: .+|Merge .+|fixup! .+|squash! .+|Revert ".+")/;

export function checkCommitPrefix(subject: string): Decision {
  if (COMMIT_PREFIX_RE.test(subject)) {
    return decide("allow", `commit subject "${subject}" matches the required prefix form`);
  }
  return decide(
    "block",
    `commit subject "${subject}" does not match the required form ` +
      `${COMMIT_PREFIX_RE.source} (e.g. "#12: add the commit-prefix guard")`,
  );
}
